/**
 * OpenJoey Response Generator - Kimi K2.5 Call #2
 * Converts analysis context to structured AI response
 */

import type { AnalysisContext } from "./tool_router.js";
import { callKimiAPI } from "../../kimi-client.js";

export interface GeneratedResponse {
  summary: string;
  key_data: string;
  market_sentiment: string;
  ai_insight: string;
  risk_note: string;
  suggestions?: string[];
}

/**
 * Generate structured response using Kimi K2.5
 */
export async function generateResponse(
  analysisContext: AnalysisContext,
  originalMessage: string,
): Promise<GeneratedResponse> {
  const systemPrompt = `You are Joey, a professional and friendly AI trading assistant.

Rules:
- Use ONLY provided analysis_context data.
- Do NOT invent numbers.
- Be conversational but concise.
- Provide insights, not financial advice.
- Explain risk when needed.
- Use clear sections.

Output format - return ONLY valid JSON:
{
  "summary": "Brief summary of the analysis",
  "key_data": "Key metrics formatted with emojis",
  "market_sentiment": "Sentiment description",
  "ai_insight": "Your professional insight",
  "risk_note": "Risk warning or note",
  "suggestions": ["Follow-up question 1", "Follow-up question 2"]
}`;

  const userPrompt = `Analysis context:
${JSON.stringify(analysisContext, null, 2)}

Original user message:
${originalMessage}

Generate a structured response as JSON.`;

  try {
    // Call Kimi K2.5 for response generation
    const response = await callKimiAPI({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.7,
      max_tokens: 1500,
    });

    const content = response.choices[0]?.message?.content || "";

    // Extract JSON from response
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON found in Kimi response");
    }

    const parsed = JSON.parse(jsonMatch[0]);

    const result: GeneratedResponse = {
      summary: parsed.summary || "Analysis complete.",
      key_data: parsed.key_data || "",
      market_sentiment: parsed.market_sentiment || "Sentiment data unavailable.",
      ai_insight: parsed.ai_insight || "Analysis based on available data.",
      risk_note: parsed.risk_note || "Always trade responsibly.",
      suggestions: parsed.suggestions || [
        "What are the resistance levels?",
        "Show me the chart",
        "Set price alert",
      ],
    };

    console.log("Response generated by Kimi K2.5:", result);
    return result;
  } catch (error) {
    console.error("Error generating response with Kimi:", error);
    console.log("Falling back to rule-based response generation...");

    // Fallback to rule-based generation
    return generateResponseFallback(analysisContext, originalMessage);
  }
}

/**
 * Fallback rule-based response generation
 */
function generateResponseFallback(
  analysisContext: AnalysisContext,
  _originalMessage: string,
): GeneratedResponse {
  const response: GeneratedResponse = {
    summary: "",
    key_data: "",
    market_sentiment: "",
    ai_insight: "",
    risk_note: "",
    suggestions: [],
  };

  // Generate summary
  if (analysisContext.asset && analysisContext.asset !== "UNKNOWN") {
    response.summary = `Here's my analysis of ${analysisContext.asset}:`;
  } else {
    response.summary =
      "I can help you with market analysis, portfolio tracking, and trading insights.";
  }

  // Generate key data section
  if (analysisContext.asset && analysisContext.asset !== "UNKNOWN") {
    let keyData = `💰 Price: Data unavailable\n`;
    keyData += `📈 Trend: ${analysisContext.trend?.toUpperCase() || "UNKNOWN"}\n`;
    keyData += `🔥 Signal: ${analysisContext.signal?.toUpperCase() || "NONE"} (${analysisContext.confidence || 0}% confidence)\n`;

    if (analysisContext.rsi) {
      let rsiStatus = "Neutral";
      if (analysisContext.rsi < 30) rsiStatus = "Oversold";
      if (analysisContext.rsi > 70) rsiStatus = "Overbought";
      keyData += `📊 RSI: ${analysisContext.rsi.toFixed(1)} (${rsiStatus})\n`;
    }

    if (analysisContext.volatility) {
      keyData += `📊 Volatility: ${analysisContext.volatility.toFixed(1)}%\n`;
    }

    response.key_data = keyData;
  }

  // Generate market sentiment
  if (analysisContext.sentiment_score) {
    const sentiment =
      analysisContext.sentiment_score > 0.6
        ? "Positive"
        : analysisContext.sentiment_score > 0.4
          ? "Neutral"
          : "Negative";
    const volume = analysisContext.mention_volume || 0;
    response.market_sentiment = `Sentiment is ${sentiment.toLowerCase()} with ${volume} mentions across social media.`;
  } else {
    response.market_sentiment = "Sentiment data unavailable.";
  }

  // Generate AI insight
  if (analysisContext.signal && analysisContext.confidence) {
    if (analysisContext.signal === "buy" && analysisContext.confidence >= 70) {
      response.ai_insight =
        "Multiple indicators suggest a buying opportunity. Consider position sizing and risk management.";
    } else if (analysisContext.signal === "sell" && analysisContext.confidence >= 70) {
      response.ai_insight =
        "Technical indicators suggest caution. Consider taking profits or setting stop-losses.";
    } else {
      response.ai_insight =
        "Signals are mixed. Wait for clearer confirmation before making decisions.";
    }
  } else {
    response.ai_insight = "Insufficient data for confident analysis. Monitor for clearer signals.";
  }

  // Generate risk note
  if (analysisContext.volatility && analysisContext.volatility > 5) {
    response.risk_note =
      "High volatility detected. Expect rapid price movements and use appropriate risk management.";
  } else if (
    analysisContext.signal === "buy" &&
    analysisContext.confidence &&
    analysisContext.confidence < 50
  ) {
    response.risk_note = "Low confidence buy signal. Consider waiting for stronger confirmation.";
  } else if (
    analysisContext.signal === "sell" &&
    analysisContext.confidence &&
    analysisContext.confidence < 50
  ) {
    response.risk_note = "Weak sell signal. Market conditions are uncertain.";
  } else {
    response.risk_note =
      "Always trade with proper risk management and never risk more than you can afford to lose.";
  }

  // Generate suggestions
  response.suggestions = [
    "What are the resistance levels?",
    "Show me the chart",
    "Set price alert",
    "Portfolio analysis",
  ];

  return response;
}

/**
 * Format response for Telegram
 */
export function formatTelegramResponse(response: GeneratedResponse, assetSymbol?: string): string {
  let formatted = "";

  if (assetSymbol && assetSymbol !== "UNKNOWN") {
    formatted += `📊 **${assetSymbol} Analysis**\n\n`;
  }

  formatted += `**${response.summary}**\n\n`;

  if (response.key_data) {
    formatted += `**Key Data:**\n${response.key_data}\n`;
  }

  if (response.market_sentiment) {
    formatted += `**🧠 Market Sentiment:**\n${response.market_sentiment}\n`;
  }

  if (response.ai_insight) {
    formatted += `**🤖 Joey's Insight:**\n${response.ai_insight}\n`;
  }

  if (response.risk_note) {
    formatted += `**⚠️ Risk Note:**\n${response.risk_note}\n`;
  }

  return formatted;
}
